apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  type: NodePort
  selector:
    app: translation-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
